name: ParaisoVice
title: ParaisoVice [ Blog Oficial
description: Blos oficial de ParaisoVice.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Inicio
    url: /
  - title: Nosotros
    url: /about
  - title: Contacto
    url: /contact
  - title: Feed
    url: /feed.xml
email: paraisovice@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
